export {HeroSection} from "./HeroSection";
export {AboutSection} from "./AboutSection";
export {ExperienceSection} from "./ExperienceSection";
export {ServicesSection} from "./ServicesSection";
export {ProcessSection} from "./ProcessSection";
export {SkillsSection} from "./SkillsSection";
export {ProjectsSection} from "./ProjectsSection";
export {TestimonialsSection} from "./TestimonialsSection";
export {ContactSection} from "./ContactSection";
