import type {Metadata} from "next";
import {Righteous, Roboto_Flex} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";


const righteousSans = Righteous({
    variable: "--font-righteous",
    subsets: ["latin"],
    weight: "400"
});
const roboto = Roboto_Flex({
    variable: "--font-roboto",
    subsets: ["latin"],
    weight: "500"
})
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html
            lang="en"
            className={`${righteousSans.variable} ${roboto.variable} h-full antialiased  `}
        >
        <body className="min-h-full flex flex-col">
        <header>
            <Navbar/>
        </header>
        <main>
            {children}
        </main>
        <footer></footer>
        </body>
        </html>
    );
}
